name: Trigger pipeline

on:
  workflow_run:
    workflows: ["Origin Pipeline"]
    types: requested

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get pipeline status
        id: get-pipeline-status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            console.info(JSON.stringify(context.payload.workflow_run.head_commit));
