name: Trigger pipeline

on:
  workflow_run:
    workflows: ["Origin Pipeline"]
    types: requested
#12
jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        name: Check if ref branch has migrations
        id: filter
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
          filters: |
            migrations:
              - '.github/workflows/**'

      - name: Get pipeline status
        id: get-pipeline-status
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { 
                name: workflowName, 
                conclusion, 
                status, 
                html_url: pipelineURL,
                head_commit: { message: commitMessage },
            } = context.payload.workflow_run;

            const hasMigrations = ${{ steps.filter.outputs.migrations }};

            console.info("hasMigrations", hasMigrations, typeof hasMigrations);

            const workflowLink = `<${pipelineURL}|${workflowName}>`;

            const messageMapping = {
                requested: `⏳ Pipeline ${workflowLink} is running`,
                in_progress: `⏳ Pipeline ${workflowLink} is running`,
                queued: `⏳ Pipeline ${workflowLink} is running`,
                completed: {
                    success: `✅ Pipeline ${workflowLink} completed successfully`,
                    failure: `❌ Pipeline ${workflowLink} failed`,
                    cancelled: `❌ Pipeline ${workflowLink} was cancelled`,
                    skipped: `❌ Pipeline ${workflowLink} was skipped`,
                    timed_out: `❌ Pipeline ${workflowLink} timed out`,
                    action_required: `❌ Pipeline ${workflowLink} requires action`,
                },
            }

            const statusMessage = messageMapping[status][conclusion] || messageMapping[status];
            const message = `------------------------------------------------------------------
              ${statusMessage}

              *Commit*: ${commitMessage}
              ------------------------------------------------------------------
            `;

            console.info(message);
