name: Trigger pipeline

on:
  workflow_run:
    workflows: ["Origin Pipeline"]
    types: requested

jobs:
  apply:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: dorny/paths-filter@v2
        name: Check if PR has migrations
        id: filter
        with:
          ref: ${{ github.event.workflow_run.head_commit.id }}
          filters: |
            migrations:
              - '.github/workflows/**'

      - name: Execute migrations
        working-directory: workspaces/server
        if: steps.filter.outputs.migrations == 'true'
        run: echo "Migrations executed"
