name: Branch lifecycle

on:
    delete:
    pull_request:
        types: [closed]

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
        - name: Github context
          run: echo "${{ toJson(github) }}"
        
        - name: Get branch name
          run: |
                DELETED_BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.ref')
                PULL_REQUEST_HEAD_BRANCH=$(cat ${{ github.event_path }} | jq --raw-output '.pull_request.head.ref')

                echo "BRANCH_NAME=${DELETED_BRANCH:-$PULL_REQUEST_HEAD_BRANCH} >> $GITHUB_ENV

        - name: Echo branch name
          run: echo $BRANCH_NAME

                