name: Branch lifecycle

on:
    delete:
    pull_request:
        types: [closed]

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
        - name: Github context
          run: echo "${{ toJson(github) }}"
        
        - name: Get branch name
          run: |
                if [ "${{ github.event_name }}" == "delete" ]; then
                    BRANCH_NAME=$(cat ${{ github.event }} | jq --raw-output '.ref')
                else
                    BRANCH_NAME=$(echo "${{ github.event.pull_request.head.ref }}" | sed 's/refs\/heads\///g')
                fi

                echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV

        - name: Echo branch name
          run: echo $BRANCH_NAME

                