name: Branch lifecycle

on:
    delete:
    pull_request:
        types: [closed]

env:
    INFRA_ID: ${{ github.head_ref || github.ref }}

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
        - name: Echo infra_id
          run: echo $INFRA_ID ${{ env.INFRA_ID }}