name: Branch lifecycle

on:
    push:
        branches-ignore: [main]

    pull_request:
        branches-ignore: [main]
        types: [closed]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - name: Print branch name
          run: echo "Relationed branchs -> ${{ github.ref }}, ${{ github.head_ref }}, ${{ github.base_ref }}. Pull request -> ${{ github.event.pull_request.number }}, ${{ github.event.pull_request.head.ref }}, ${{ github.event.pull_request.base.ref }}, ${{ github.event.pull_request.merged }}"