name: Branch lifecycle

on:
    delete:
    pull_request:
        types: [closed]

env:
    INFRA_ID: ${{  github.event.pull_request.head.ref && github.head_ref || github.ref }}

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
        - name: Echo infra_id
          run: echo $INFRA_ID ${{ github.event.pull_request.head.ref }} a ${{ github.head_ref }} a ${{ github.ref }}