name: Terraform apply

on:
    push:

jobs:
    destroy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Get branch name
          run: |
              BRANCH_NAME=$(echo ${GITHUB_REF#refs/heads/})
              echo "BRANCH_NAME=$BRANCH_NAME" >> $GITHUB_ENV
      
        - name: Configure AWS Credentials
          uses: aws-actions/configure-aws-credentials@v3
          with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-1

        - name: Terraform init
          working-directory: terraform
          run: terraform init

        - name: Set up workspace
          working-directory: terraform
          run: terraform workspace select ${{ env.BRANCH_NAME }} || terraform workspace new ${{ env.BRANCH_NAME }}

        - name: Terraform destroy
          working-directory: terraform
          run: terraform apply -auto-approve
                